Repository everyones-lck/lck-android, pull requests merged in 2024-08, with the labels that each got.

#20 [UI/#19] 뷰잉파티 채팅 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/everyones/lck/domain/model/party/ChatItem.kt
  app/src/main/java/umc/everyones/lck/domain/model/party/ViewingPartyItem.kt
  app/src/main/java/umc/everyones/lck/presentation/MainActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/community/CommunityFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/PostListFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/read/ReadPostActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/community/read/ReadPostViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/community/write/WritePostActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/community/write/WritePostViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/home/HomeFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/match/TodayMatchFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/match/TodayMatchTodayPogFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/party/ViewingPartyChatActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/party/ViewingPartyFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/adapter/ChatRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/party/adapter/ParticipantsRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/party/adapter/ViewingPartyRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ParticipantsFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ReadViewingPartyFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/write/WriteViewingPartyActivity.kt
  app/src/main/res/drawable/ic_chat.xml
  app/src/main/res/drawable/shape_rect_receiver_chat_bg.xml
  app/src/main/res/drawable/shape_rect_sender_chat_bg.xml
  app/src/main/res/layout/activity_read_post.xml
  app/src/main/res/layout/activity_viewing_party_chat.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_participants.xml
  app/src/main/res/layout/fragment_read_viewing_party.xml
  app/src/main/res/layout/fragment_today_match.xml
  app/src/main/res/layout/item_participant.xml
  app/src/main/res/layout/item_receiver_chat.xml
  app/src/main/res/layout/item_sender_chat.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/colors.xml
Labels: 김규진, UI 🖌

#24 [ADD/#21] 뷰잉파티 api 연결 세팅
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/everyones/lck/data/datasource/ViewingPartyDataSource.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/ViewingPartyDataSourceImpl.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/party/WriteViewingPartyRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/CommonViewingPartyResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/JoinViewingPartyResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ReadViewingPartyResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ViewingPartyChatLogResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ViewingPartyChatRoomResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ViewingPartyListResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ViewingPartyParticipantsResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/repositoryImpl/party/ViewingPartyRepositoryImpl.kt
  app/src/main/java/umc/everyones/lck/data/service/party/ViewingPartyService.kt
  app/src/main/java/umc/everyones/lck/di/DataSourceModule.kt
  app/src/main/java/umc/everyones/lck/di/DataStoreModule.kt
  app/src/main/java/umc/everyones/lck/di/NetworkModule.kt
  app/src/main/java/umc/everyones/lck/di/RepositoryModule.kt
  app/src/main/java/umc/everyones/lck/di/ServiceModule.kt
  app/src/main/java/umc/everyones/lck/domain/model/party/ViewingPartyItem.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/party/WriteViewingPartyModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/party/CommonViewingPartyModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/party/JoinViewingPartyModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/party/ReadViewingPartyModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/party/ViewingPartyChatLogModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/party/ViewingPartyChatRoomModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/party/ViewingPartyListModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/party/ViewingPartyParticipantsModel.kt
  app/src/main/java/umc/everyones/lck/domain/repository/party/ViewingPartyRepository.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/party/ViewingPartyFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/ViewingPartyViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/party/adapter/ViewingPartyRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/party/chat/ViewingPartyChatActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/party/chat/ViewingPartyChatViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ParticipantsFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ReadViewingPartyFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ReadViewingPartyViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/party/write/WriteViewingPartyActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/party/write/WriteViewingPartyViewModel.kt
  app/src/main/java/umc/everyones/lck/util/extension/EditTextExt.kt
  app/src/main/java/umc/everyones/lck/util/extension/StringExt.kt
  app/src/main/java/umc/everyones/lck/util/network/AuthInterceptor.kt
  app/src/main/res/layout/activity_write_viewing_party.xml
  app/src/main/res/layout/fragment_read_viewing_party.xml
  app/src/main/res/navigation/main_graph.xml
Labels: 김규진, ADD ➕

#28 [Feat/#26] 뷰잉파티 글목록 기능 구현
  app/build.gradle.kts
  app/src/main/java/umc/everyones/lck/data/datasource/NaverDataSource.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/naver/NaverDataSourceImpl.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/party/ViewingPartyDataSourceImpl.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/party/ViewingPartyListPagingSource.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/party/WriteViewingPartyRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/naver/geocoding/GeocodingResponse.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/naver/geocoding/GeocodingResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/naver/reversegeocoding/Land.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/naver/reversegeocoding/LandInfo.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/naver/reversegeocoding/ReverseGeocodingResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ReadViewingPartyResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ViewingPartyListResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/repositoryImpl/NaverRepositoryImpl.kt
  app/src/main/java/umc/everyones/lck/data/repositoryImpl/party/ViewingPartyRepositoryImpl.kt
  app/src/main/java/umc/everyones/lck/data/service/NaverService.kt
  app/src/main/java/umc/everyones/lck/di/DataSourceModule.kt
  app/src/main/java/umc/everyones/lck/di/RepositoryModule.kt
  app/src/main/java/umc/everyones/lck/domain/model/naver/GeocodingModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/naver/ReverseGeocodingModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/party/WriteViewingPartyModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/party/ViewingPartyListModel.kt
  app/src/main/java/umc/everyones/lck/domain/repository/NaverRepository.kt
  app/src/main/java/umc/everyones/lck/domain/repository/party/ViewingPartyRepository.kt
  app/src/main/java/umc/everyones/lck/presentation/MainActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/base/BaseFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/ViewingPartyFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/ViewingPartyViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/party/adapter/ViewingPartyRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ReadViewingPartyFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/write/WriteViewingPartyActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/party/write/WriteViewingPartyViewModel.kt
  app/src/main/java/umc/everyones/lck/util/extension/NavigationBarExt.kt
  app/src/main/java/umc/everyones/lck/util/extension/StringExt.kt
  app/src/main/java/umc/everyones/lck/util/network/UiState.kt
  app/src/main/res/layout/activity_write_viewing_party.xml
  app/src/main/res/layout/fragment_read_viewing_party.xml
  app/src/main/res/layout/fragment_viewing_party.xml
  app/src/main/res/layout/item_viewing_party.xml
  app/src/main/res/navigation/main_graph.xml
Labels: 김규진, FEAT ✨

#30 [FEAT/#29] 뷰잉파티 글작성/글수정 기능 구현
  app/src/main/java/umc/everyones/lck/data/dto/request/party/WriteViewingPartyRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ReadViewingPartyResponseDto.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/party/WriteViewingPartyModel.kt
  app/src/main/java/umc/everyones/lck/presentation/MainActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/party/ViewingPartyFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/ViewingPartyViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/party/adapter/ParticipantsRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/party/adapter/ViewingPartyRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ParticipantsFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ReadViewingPartyFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ReadViewingPartyViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/party/write/WriteViewingPartyActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/party/write/WriteViewingPartyViewModel.kt
  app/src/main/java/umc/everyones/lck/util/network/EventFlow.kt
Labels: 김규진, FEAT ✨

#34 [FEAT/#33] 커뮤니티 기능 구현
  app/src/main/java/umc/everyones/lck/data/datasource/community/CommunityDataSource.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/community/CommunityDataSourceImpl.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/community/CommunityListPagingSource.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/community/CreateCommentRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/community/EditCommunityRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/community/WriteCommunityRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/NonBaseResponse.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/community/CommunityListResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/community/EditCommunityResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/community/ReadCommunityResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/community/WriteCommunityResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ReadViewingPartyResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/party/ViewingPartyListResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/repositoryImpl/community/CommunityRepositoryImpl.kt
  app/src/main/java/umc/everyones/lck/data/service/community/CommunityService.kt
  app/src/main/java/umc/everyones/lck/di/DataSourceModule.kt
  app/src/main/java/umc/everyones/lck/di/RepositoryModule.kt
  app/src/main/java/umc/everyones/lck/di/ServiceModule.kt
  app/src/main/java/umc/everyones/lck/domain/model/community/CommunityListModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/community/EditPost.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/community/CreateCommentRequestModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/community/EditCommunityRequestModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/community/WriteCommunityRequestModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/community/EditCommunityResponseModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/community/ReadCommunityResponseModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/community/WriteCommunityResponseModel.kt
  app/src/main/java/umc/everyones/lck/domain/repository/community/CommunityRepository.kt
  app/src/main/java/umc/everyones/lck/presentation/MainActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/community/CommunityFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/CommunityViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/community/PostListFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/adapter/CommentRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/community/adapter/PostListRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/community/adapter/PostListVPA.kt
  app/src/main/java/umc/everyones/lck/presentation/community/list/FreeAgentListFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/list/PostListFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/list/QuestionListFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/list/ReviewListFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/list/SmallTalkListFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/list/SupportListFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/list/TradeListFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/community/read/ReadPostActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/community/read/ReadPostViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/community/write/WritePostActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/community/write/WritePostViewModel.kt
  app/src/main/java/umc/everyones/lck/util/extension/ContextExt.kt
  app/src/main/java/umc/everyones/lck/util/extension/StringExt.kt
  app/src/main/res/layout/activity_write_post.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_community_post.xml
Labels: 김규진, FEAT ✨

#35 Add/#22 user api 연결 세팅
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/everyones/lck/EveryonesLCKApplication.kt
  app/src/main/java/umc/everyones/lck/User.kt
  app/src/main/java/umc/everyones/lck/data/SignupUserData.kt
  app/src/main/java/umc/everyones/lck/data/TeamData.kt
  app/src/main/java/umc/everyones/lck/data/datasource/login/LoginDataSource.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/LoginDataSourceImpl.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/login/CommonLoginRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/login/NicknameAuthUserRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/login/SignupAuthUserRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/login/CommonLoginResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/repositoryImpl/login/LoginRepositoryImpl.kt
  app/src/main/java/umc/everyones/lck/data/service/LoginService.kt
  app/src/main/java/umc/everyones/lck/di/NetworkModule.kt
  app/src/main/java/umc/everyones/lck/di/RepositoryModule.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/login/CommonLoginRequestModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/login/NicknameAuthUserRequestModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/login/CommonLoginResponseModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/user/UserItem.kt
  app/src/main/java/umc/everyones/lck/domain/repository/login/LoginRepository.kt
  app/src/main/java/umc/everyones/lck/presentation/SplashActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/community/CommunityFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/LoginFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupMyteamFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupNicknameFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupProfileFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupSuccessFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/umc/everyones/lck/util/AuthCodeHandlerActibity.kt
  app/src/main/java/umc/everyones/lck/util/TeamUtils.kt
  app/src/main/res/drawable/ic_logo_image.png
  app/src/main/res/drawable/shape_dialog_button_confirm_background.xml
  app/src/main/res/drawable/shape_rect_12_gray_line.xml
  app/src/main/res/drawable/shape_rect_12_green_line.xml
  app/src/main/res/drawable/shape_rect_4_green_line.xml
  app/src/main/res/drawable/shape_rect_4_red_line.xml
  app/src/main/res/layout/dialog_nickname_confirm.xml
  app/src/main/res/layout/fragment_signup_nickname.xml
  app/src/main/res/values/colors.xml
  settings.gradle.kts
Labels: ADD ➕, 김승혁

#38 [CHORE#31] 병합 후 충돌 해결
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/ViewingPartyDataSourceImpl.kt
  app/src/main/java/umc/everyones/lck/data/service/party/ViewingPartyService.kt
Labels: CHORE 🎀

#39 Add/#28 mypage api 연결 세팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/everyones/lck/data/TeamData.kt
  app/src/main/java/umc/everyones/lck/data/UpdateProfileRequest.kt
  app/src/main/java/umc/everyones/lck/data/datasource/MypageDataSource.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/MypageDataSourceImpl.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/mypage/CancelHostViewingPartyMypageRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/mypage/CancelParticipateViewingPartyMypageRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/mypage/UpdateProfilesRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/request/mypage/UpdateTeamRequestDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/mypage/CommentsMypageResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/mypage/HostViewingPartyMypageResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/mypage/InquiryProfilesResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/mypage/ParticipateViewingPartyMypageResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/mypage/PostsMypageResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/mypage/UpdateProfilesResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/repositoryImpl/mypage/MypageRepositoryImpl.kt
  app/src/main/java/umc/everyones/lck/data/service/MypageService.kt
  app/src/main/java/umc/everyones/lck/di/DataStoreModule.kt
  app/src/main/java/umc/everyones/lck/di/NetworkModule.kt
  app/src/main/java/umc/everyones/lck/di/RepositoryModule.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/mypage/CancelHostViewingPartyMypageModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/mypage/CancelParticipateViewingPartyMypageModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/request/mypage/UpdateTeamModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/mypage/CommentsMypageModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/mypage/HostViewingPartyMypageModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/mypage/InquiryProfilesModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/mypage/ParticipateViewingPartyMypageModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/mypage/PostsMypageModel.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/mypage/UpdateProfilesModel.kt
  app/src/main/java/umc/everyones/lck/domain/repository/MypageRepository.kt
  app/src/main/java/umc/everyones/lck/presentation/login/LoginFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupMyteamFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageMyteamFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageProfileFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageProfileWithdrawFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageViewModel.kt
  app/src/main/res/layout/fragment_mypage_main.xml
  app/src/main/res/layout/fragment_mypage_profile_withdraw.xml
  app/src/main/res/values/appearances.xml
Labels: ADD ➕, 김승혁

#41 [CHORE/#31] 병합 후 충돌 해결
  app/src/main/java/umc/everyones/lck/di/RepositoryModule.kt
Labels: 김규진, CHORE 🎀

#43 Add/#28 로그아웃 구현
  app/src/main/java/umc/everyones/lck/data/datasource/MypageDataSource.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/MypageDataSourceImpl.kt
  app/src/main/java/umc/everyones/lck/data/repositoryImpl/mypage/MypageRepositoryImpl.kt
  app/src/main/java/umc/everyones/lck/data/service/MypageService.kt
  app/src/main/java/umc/everyones/lck/domain/repository/MypageRepository.kt
  app/src/main/java/umc/everyones/lck/presentation/SplashActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/home/HomeFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/LoginFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupMyteamFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageProfileFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageProfileWithdrawFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/umc/everyones/lck/util/LoginManager.kt
  app/src/main/java/umc/everyones/lck/util/NicknameManager.kt
  app/src/main/res/layout/fragment_mypage_profile_edit.xml
Labels: ADD ➕, 김승혁

#44 [CHORE/#23] UI 수정
  app/src/main/java/umc/everyones/lck/presentation/home/HomeFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/match/TodayMatchLckPogFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/match/TodayMatchTodayPogFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_today_match_prediction.xml
  app/src/main/res/layout/fragment_today_match_today_pog.xml
  app/src/main/res/layout/item_lck_pog_player.xml
  app/src/main/res/layout/item_today_pog_player.xml
Labels: CHORE 🎀, 김기찬

#51 [ADD/#47] About LCK 기능 수정
  app/src/main/java/umc/everyones/lck/presentation/lck/AboutLckClRoasterFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/lck/AboutLckCoachesFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/lck/AboutLckRoasterFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/lck/AboutLckTeamPlayerFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/lck/adapter/PlayerAdapter.kt
  app/src/main/res/layout/fragment_about_lck_cl_roaster.xml
  app/src/main/res/layout/fragment_about_lck_coaches.xml
  app/src/main/res/layout/fragment_about_lck_roaster.xml
  app/src/main/res/layout/fragment_about_lck_team.xml
  app/src/main/res/layout/fragment_about_lck_team_player.xml
Labels: ADD ➕

#54 [Mod/#53] About LCK UI 수정
  app/src/main/res/layout/fragment_about_lck.xml
Labels: UI 🖌, 장효원

#52 [FEAT/#46] 마이페이지 기능 구현
  app/src/main/java/umc/everyones/lck/data/TeamData.kt
  app/src/main/java/umc/everyones/lck/data/datasource/login/LoginDataSource.kt
  app/src/main/java/umc/everyones/lck/data/datasourceImpl/LoginDataSourceImpl.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/login/CommonLoginResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/dto/response/login/LoginResponseDto.kt
  app/src/main/java/umc/everyones/lck/data/repositoryImpl/login/LoginRepositoryImpl.kt
  app/src/main/java/umc/everyones/lck/data/service/LoginService.kt
  app/src/main/java/umc/everyones/lck/data/service/MypageService.kt
  app/src/main/java/umc/everyones/lck/domain/model/response/login/LoginResponseModel.kt
  app/src/main/java/umc/everyones/lck/domain/repository/login/LoginRepository.kt
  app/src/main/java/umc/everyones/lck/presentation/login/LoginFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupSuccessFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/login/SignupViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageMyteamFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageProfileEditFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageProfileFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageViewModel.kt
  app/src/main/res/layout/fragment_mypage_main.xml
  app/src/main/res/layout/fragment_mypage_profile.xml
  app/src/main/res/layout/fragment_mypage_profile_edit.xml
  app/src/main/res/navigation/mypage_graph.xml
Labels: FEAT ✨, 김승혁

#59 [MOD/#57] 뷰잉파티 사전 점검 내용 수정
  app/src/main/java/umc/everyones/lck/presentation/base/BaseDialogFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/party/adapter/ParticipantsRVA.kt
  app/src/main/java/umc/everyones/lck/presentation/party/chat/ViewingPartyChatActivity.kt
  app/src/main/java/umc/everyones/lck/presentation/party/dialog/JoinViewingPartyDialogFragment.kt
  app/src/main/res/layout/dialog_join_viewing_party.xml
  app/src/main/res/layout/item_participant.xml
Labels: 김규진

#60 [Feat/#56] mypage my profile 수정 구현
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageProfileEditFragment.kt
  app/src/main/java/umc/everyones/lck/presentation/mypage/MyPageViewModel.kt
  app/src/main/java/umc/everyones/lck/presentation/party/read/ReadViewingPartyFragment.kt
  app/src/main/res/layout/fragment_mypage_profile_edit.xml
  app/src/main/res/layout/fragment_mypage_profile_withdraw.xml
  app/src/main/res/layout/fragment_read_viewing_party.xml
Labels: FEAT ✨, 김승혁
